// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eefwldwtvfsfvabbhsku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlZndsZHd0dmZzZnZhYmJoc2t1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTIzMjUsImV4cCI6MjA3Mzg2ODMyNX0.FWPLCtQ7R4HYN37BAATYETqeVi2lLfkd3_F5KWCGVTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});